airline_dic = {
    "AS": "Alaska Airlines",
    "FX": "FedEx Express",
    "PO": "Polar Air Cargo",
    "N8": "National Airlines",
    "5Y": "Atlas Air",
    "B6": "JetBlue",
    "7H": "Ravn Alaska",
    "HA": "Hawaiian Airlines",
    "DL": "Delta Air Lines",
    "AA": "American Airlines",
    "UA": "United Airlines",
    "GB": "ABX Air",
    "5X": "UPS Airlines",
    "F9": "Frontier Airlines",
    "NK": "Spirit Airlines",
}